# Generated by Django 5.1.4 on 2025-01-13 13:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True)),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_de_modificacao', models.DateTimeField(auto_now=True)),
                ('data_de_inicio', models.DateField()),
                ('hora_de_inicio', models.TimeField()),
                ('hora_de_termino', models.TimeField()),
                ('horas_utilizadas', models.TimeField()),
                ('ticket', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
