# Generated by Django 5.1.4 on 2025-01-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_horas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='hora_de_termino',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='horas_utilizadas',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
