# Generated by Django 5.1.4 on 2025-01-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_horas', '0002_alter_registro_hora_de_termino_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro',
            options={'ordering': ['-data_de_inicio', '-hora_de_inicio']},
        ),
        migrations.AlterField(
            model_name='registro',
            name='horas_utilizadas',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
