# Generated by Django 5.1.4 on 2025-01-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_horas', '0003_alter_registro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
